name: Close PR

on:
  pull_request:
    types:
      - closed

jobs:
  send-number:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number ğŸ“
        run: |
          mkdir -p ./prnumber
          echo ${{ github.event.number }} > ./prnumber/prnumber.txt

      - name: Upload PR number ğŸ“¤
        uses: actions/upload-artifact@v2
        with:
          name: prnumber
          path: prnumber/
